### ISSUE TITLE
World quest tracking overlaps with regular tracked quests

### ISSUE THREAD

**Issue by jadinm** [Tercioo/World-Quest-Tracker#103]
Game version: 11.0.0.55824
WQT version: v11.0.0.499-Retail

World quest tracking overlaps with regular tracked quests instead of being appended to the tracked quests as it used to be before the pre-patch release.

![Capture d'écran 2024-07-25 221738](https://github.com/user-attachments/assets/4e966060-ac5a-48fa-80de-bc238d8700ba)

**Comment by Tercioo** [comment]
fixed
