### ISSUE TITLE
Two bugs

### ISSUE THREAD

**Issue by Neurotoxin001** [Tercioo/World-Quest-Tracker#11]
1. When I click on horde/alliance icon it shows me legion WQ's, not BFA
2. When I select some WQ's and left click on them – nothing happens. Before prepatch it's was start tracking the quest in blizzard UI, like it doing now when I shift+click on WQ's on the world map

v 9.0.1.400

**Comment by Neurotoxin001** [comment]
v 9.0.1.403 still have these.

**Comment by dakhran** [comment]
Possible fix for the Horde/Alliance icons:

Edit WorldQuestTracker_Core.lua
Lines 824 and 857, change 50 to 45.
Lines 827 and 860, change 60 to 50.

It seems like level assumptions were being made that were incorrect.

**Comment by Neurotoxin001** [comment]
1. fixed in v9.0.1.404
2. still here

**Comment by Neurotoxin001** [comment]
2. fixed in v9.0.1.405
