### ISSUE TITLE
Couldn't find inherited node "MicroButtonAlertTemplate"

### ISSUE THREAD

**Issue by NORPG** [Tercioo/World-Quest-Tracker#14]
22x ...rfaceWorldQuestTracker\WorldQuestTracker.lua:831: CreateFrame(): Couldn't find inherited node "MicroButtonAlertTemplate"
[string "=[C]"]: in function `CreateFrame'
[string "@WorldQuestTracker\WorldQuestTracker.lua"]:831: in function <...rfaceWorldQuestTracker\WorldQuestTracker.lua:827>

**Comment by andywy119** [comment]
open "WorldQuestTracker.lua" file, use"MicroButtonAlertTemplate_BFA" replace "MicroButtonAlertTemplate"

**Comment by NORPG** [comment]
#16
