### ISSUE TITLE
Lua error in dungeon

### ISSUE THREAD

**Issue by Nils89** [Tercioo/World-Quest-Tracker#67]
Got this in an dungeon:

358x WorldQuestTracker/WorldQuestTracker_Core.lua:1527: bad argument #1 to 'sin' (number expected, got nil)
[string "=[C]"]: in function `sin'
[string "@WorldQuestTracker/WorldQuestTracker_Core.lua"]:1527: in function <WorldQuestTracker/WorldQuestTracker_Core.lua:1521>

Locals:
(*temporary) = nil
(*temporary) = "number expected, got nil"

**Comment by Tercioo** [comment]
thanks, sent new version with fixes for your bug reports today

------ Original Message ------
From: "Glow" ***@***.***>
To: "Tercioo/World-Quest-Tracker" 
***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 29-Nov-22 5:59:10 PM
Subject: [Tercioo/World-Quest-Tracker] Lua error in dungeon (Issue #67)
