### ISSUE TITLE
Enable/Disable Quest Tracker has no effect

### ISSUE THREAD

**Issue by fubaWoW** [Tercioo/World-Quest-Tracker#69]
hi there,

whether if the "Enable Quest Tracker" checkbox is enabled or disabled make no difference, the World Quest Tracker ALWAYS hook into the Questtracker.

"Custom Position" is possible but also ALWAYS visible, no matter the "Enable Quest Tracker" is enabled or not!

![image](https://user-images.githubusercontent.com/41425685/204956722-576f46d0-3bf2-4f98-a145-59836e8159de.png)

**Comment by Tercioo** [comment]
fixed! thank you

**Comment by fubaWoW** [comment]
thanks!
